In [3]:
import torch
import torch.nn as nn

In [5]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[3., 0., 4., 4., 0., 3.],
         [3., 0., 1., 3., 4., 1.],
         [0., 1., 0., 0., 1., 2.],
         [4., 1., 2., 3., 3., 4.],
         [3., 0., 1., 0., 0., 1.],
         [4., 0., 0., 0., 3., 1.]]])

In [6]:
#define convolutional layer
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3,
                       bias=False)

In [7]:
conv_layer.weight

Parameter containing:
tensor([[[[-0.0761,  0.0875,  0.2223],
          [ 0.0539,  0.2019, -0.0592],
          [-0.0284, -0.3146, -0.2149]]]], requires_grad=True)

In [8]:
init_kernel_weight = torch.randint(high=2,
                                   size=(conv_layer.weight.data.shape),
                                   dtype=torch.float32)

In [9]:
#init weight
conv_layer.weight.data = init_kernel_weight

In [10]:
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 0., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [11]:
output = conv_layer(input)
output

tensor([[[ 7.,  5.,  5.,  9.],
         [10.,  7., 10., 11.],
         [ 4.,  1.,  2.,  3.],
         [10.,  4.,  8.,  8.]]], grad_fn=<SqueezeBackward1>)

In [12]:
input

tensor([[[3., 0., 4., 4., 0., 3.],
         [3., 0., 1., 3., 4., 1.],
         [0., 1., 0., 0., 1., 2.],
         [4., 1., 2., 3., 3., 4.],
         [3., 0., 1., 0., 0., 1.],
         [4., 0., 0., 0., 3., 1.]]])

In [13]:
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3)

In [14]:
init_kernel_weight

tensor([[[[1., 0., 1.],
          [0., 0., 0.],
          [1., 0., 1.]]]])

In [15]:
#init weight
conv_layer.weight.data = init_kernel_weight
conv_layer

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [16]:
conv_layer.bias

Parameter containing:
tensor([0.0302], requires_grad=True)

In [17]:
#init bias
conv_layer.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))

In [18]:
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [20]:
output = conv_layer(input)
output

tensor([[[ 8.,  6.,  6., 10.],
         [11.,  8., 11., 12.],
         [ 5.,  2.,  3.,  4.],
         [11.,  5.,  9.,  9.]]], grad_fn=<SqueezeBackward1>)