In [1]:
import torch
import torch.nn as nn

In [2]:
input = torch.randint(5, (1, 4, 4), dtype=torch.float32)
input

tensor([[[0., 3., 4., 2.],
         [2., 3., 2., 1.],
         [1., 3., 1., 4.],
         [4., 3., 4., 0.]]])

In [4]:
init_kernel_weight = torch.randint(high=2,
                                   size=(1, 1, 3, 3),
                                   dtype=torch.float32)
init_kernel_weight

tensor([[[[0., 0., 1.],
          [1., 1., 0.],
          [0., 0., 1.]]]])

In [5]:
#define convolution layer
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3,
                       padding='same')

In [6]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[0., 0., 1.],
          [1., 1., 0.],
          [0., 0., 1.]]]], requires_grad=True)

In [7]:
#init bias
conv_layer.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [8]:
output = conv_layer(input)
output

tensor([[[ 4.,  6.,  9.,  7.],
         [ 9., 11., 12.,  4.],
         [ 8., 11.,  6.,  6.],
         [ 8.,  9., 12.,  5.]]], grad_fn=<SqueezeBackward1>)

In [9]:
input

tensor([[[0., 3., 4., 2.],
         [2., 3., 2., 1.],
         [1., 3., 1., 4.],
         [4., 3., 4., 0.]]])

In [12]:
#define convolution layer
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3,
                       padding=(2,1))

In [14]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[0., 0., 1.],
          [1., 1., 0.],
          [0., 0., 1.]]]], requires_grad=True)

In [15]:
#init bias
conv_layer.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [16]:
output = conv_layer(input)
output

tensor([[[ 4.,  5.,  3.,  1.],
         [ 4.,  6.,  9.,  7.],
         [ 9., 11., 12.,  4.],
         [ 8., 11.,  6.,  6.],
         [ 8.,  9., 12.,  5.],
         [ 4.,  5.,  1.,  1.]]], grad_fn=<SqueezeBackward1>)