In [8]:
import torch
import torch.nn as nn

In [9]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[0., 2., 3., 2., 4., 1.],
         [2., 2., 2., 1., 0., 0.],
         [4., 3., 2., 0., 2., 4.],
         [3., 0., 4., 2., 0., 2.],
         [0., 2., 2., 2., 2., 1.],
         [2., 1., 4., 4., 0., 2.]]])

In [10]:
#define convolutional layer
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3,
                       stride=2)

In [11]:
init_kernel_weight = torch.randint(high=2,
                                   size=(1, 1, 3, 3),
                                   dtype=torch.float32)
init_kernel_weight

tensor([[[[1., 1., 0.],
          [0., 1., 1.],
          [0., 0., 1.]]]])

In [12]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 0.],
          [0., 1., 1.],
          [0., 0., 1.]]]], requires_grad=True)

In [13]:
#init bias
conv_layer.bias = nn.Parameter(torch.tensor([1], dtype=torch.float32))
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [14]:
output = conv_layer(input)
output

tensor([[[ 9.,  9.],
         [14.,  7.]]], grad_fn=<SqueezeBackward1>)