In [1]:
import torch
import torch.nn as nn

In [2]:
input = torch.randint(5, (1, 6, 6), dtype= torch.float32)
input

tensor([[[3., 4., 4., 2., 4., 1.],
         [1., 2., 3., 4., 0., 2.],
         [4., 4., 3., 2., 4., 0.],
         [0., 1., 4., 4., 0., 4.],
         [0., 1., 2., 1., 1., 1.],
         [1., 4., 1., 3., 4., 1.]]])

In [3]:
avg_pooling_layer = nn.AvgPool2d(kernel_size=(3,2),
                                 stride=(2, 2))

In [4]:
output = avg_pooling_layer(input)
output

tensor([[[3.0000, 3.0000, 1.8333],
         [1.6667, 2.6667, 1.6667]]])

In [5]:
input

tensor([[[3., 4., 4., 2., 4., 1.],
         [1., 2., 3., 4., 0., 2.],
         [4., 4., 3., 2., 4., 0.],
         [0., 1., 4., 4., 0., 4.],
         [0., 1., 2., 1., 1., 1.],
         [1., 4., 1., 3., 4., 1.]]])

In [6]:
avg_pooling_layer = nn.AvgPool1d(kernel_size=3,
                                 stride=3)


In [7]:
output = avg_pooling_layer(input)
output

tensor([[[3.6667, 2.3333],
         [2.0000, 2.0000],
         [3.6667, 2.0000],
         [1.6667, 2.6667],
         [1.0000, 1.0000],
         [2.0000, 2.6667]]])